services:
  mysql:
    image: mysql:latest
    container_name: jooq-multiset-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S6cZuMLwZJVohOUGZpBrM8zqZTK6NuwA
      MYSQL_DATABASE: docker-hub
      MYSQL_USER: maintainer-chipmunk
      MYSQL_PASSWORD: lHoqmsVDCkp7V1QrVTvQPj6kYMAzQwOz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
